name: Build for Windows
on: workflow_dispatch
jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: flutter --version
     - run: flutter config --no-analytics
     - run: flutter build windows
     - uses: actions/upload-artifact@v2
       with:
         name: windows_64
         path: build/windows/runner/Release/
